# Generated by Django 3.0.6 on 2020-05-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras',
            name='ip',
        ),
    ]
