# Generated by Django 3.0.6 on 2020-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cameras_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
