# Generated by Django 3.0.4 on 2020-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureTaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
