# Generated by Django 3.0.4 on 2020-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictureTaker', '0002_catlearning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catlearning',
            old_name='title',
            new_name='name',
        ),
    ]
